### ISSUE TITLE
Customization Specification Questions

### ISSUE THREAD

**Issue by kbrowns** [adamleff/knife-vsphere#191]
I've started using knife-vsphere with great success to spin up VM's in our vsphere.  Several of these are Windows, and we're getting to a point where we need to sysprep+generalize our templates so that we can clone into VM instances that have unique SID's, proper product key's, etc.  I was pleasantly surprised to find a number of useful command line switch as well as the cplugin model on the vm clone comment.  However, now that I"m trying to use it, I'm confused and a bit starved for details.

From browsing through the knife-vsphere code, it appears the command line args I'm passing into vm clone are getting built up into version Customization* objects from the rbvmomi library.  --cspec also allows me to pass a cspec name of a Customization Specification defined on vsphere.  I'm a little confused on what code like that with these issues is actually doing:

https://github.com/ezrapagel/knife-vsphere/issues/148
https://github.com/ezrapagel/knife-vsphere/issues/100

what is the difference between --cspec and all these other switch --c<foo> such as --chost?  I assume going the --cplugin route overrides any other --c<foo> passed?  If i pass a --cspec it points at a cspec on the vsphere server as I'd expect, but I would love to have this stuff codified in code and outside of vsphere, but confused by what combination of switches are require and should be mixed together.  If all I pass is a --chost like the following, then it blows up with a nil method error:

     [exec] Starting 'cmd.exe (/C knife vsphere vm clone thevm --template prius_2012r2_model --bootstrap false --start --chostname thevm -VV --vshost 'parchfooivmware.devfoo.com' --vsuser '*********' --vspass '*********' --vsinsecure true --vsdc 'PARCHTEST')' in 'C:\_code\SCM\Build\fooBuild\Scripts'
     [exec] DL is deprecated, please use Fiddle
     [exec] WARN: Ohai::Config[:log_location] is set. Ohai::Config[:log_location] is deprecated and will be removed in future releases of ohai. Use ohai.log_location in your configuration file to configure :log_location for ohai.
     [exec] WARNING: No knife configuration file found
     [exec] WARN: Ohai::Config[:log_level] is set. Ohai::Config[:log_level] is deprecated and will be removed in future releases of ohai. Use ohai.log_level in your configuration file to configure :log_level for ohai.
     [exec] DEBUG: value for config item chef_node_name: 
     [exec] DEBUG: value for config item vsphere_host: parchfooivmware.devfoo.com
     [exec] DEBUG: value for config item vsphere_path: /sdk
     [exec] DEBUG: value for config item vsphere_port: 443
     [exec] DEBUG: value for config item vsphere_nossl: 
     [exec] DEBUG: value for config item vsphere_user: devfoo\SVC_SelfProv
     [exec] DEBUG: value for config item vsphere_pass: 4eStechUsteD
     [exec] DEBUG: value for config item vsphere_insecure: true
     [exec] DEBUG: value for config item proxy_host: 
     [exec] DEBUG: value for config item proxy_port: 
     [exec] DEBUG: value for config item vsphere_dc: PARCHTEST
     [exec] DEBUG: value for config item folder: 
     [exec] DEBUG: value for config item vsphere_dc: PARCHTEST
     [exec] DEBUG: value for config item linked_clone: 
     [exec] DEBUG: value for config item resource_pool: 
     [exec] DEBUG: value for config item vsphere_dc: PARCHTEST
     [exec] DEBUG: value for config item datastore: 
     [exec] DEBUG: value for config item datastorecluster: 
     [exec] DEBUG: value for config item customization_vlan: 
     [exec] DEBUG: value for config item linked_clone: 
     [exec] DEBUG: value for config item datastore: 
     [exec] DEBUG: value for config item datastore: 
     [exec] DEBUG: value for config item datastorecluster: 
     [exec] DEBUG: value for config item thin_provision: 
     [exec] DEBUG: value for config item mark_as_template: 
     [exec] DEBUG: value for config item annotation: 
     [exec] DEBUG: value for config item customization_cpucount: 
     [exec] DEBUG: value for config item customization_memory: 
     [exec] DEBUG: value for config item customization_vlan: 
     [exec] DEBUG: value for config item customization_spec: 
     [exec] DEBUG: value for config item customization_dns_ips: 
     [exec] DEBUG: value for config item customization_dns_suffixes: 
     [exec] DEBUG: value for config item disable_customization: 
     [exec] DEBUG: Identified os as windows.
     [exec] C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:548:in `generate_clone_spec': undefined method `identification' for #<RbVmomi::VIM::CustomizationIdentitySettings:0x000000073f6770> (NoMethodError)
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:310:in `run'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/knife.rb:215:in `run'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application/knife.rb:142:in `run'
     [exec]  from C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/bin/knife:25:in `<top (required)>'
     [exec]  from C:/Tools/ruby215/bin/knife:23:in `load'
     [exec]  from C:/Tools/ruby215/bin/knife:23:in `<main>'
     [exec] C:\_code\SCM\Build\fooBuild\Scripts\Jenkins.Provision.build(139,4):
     [exec] External Program Failed: cmd.exe (return code was 1)

**Comment by swalberg** [comment]
Hi there,

#177 is probably what you're running into. We added some Windows bootstrap/winrm functionality recently and not all the paths through the code are great. Basically that identity part of the spec needs to be filled in if you're not referring to a vsphere-side cspec. I think the right answer would be to read the options from a file or JSON on the command line, otherwise we'll be adding yet more `--` options.

There's another issue that's evading me right now where it was pointed out that we throw away the spec halfway through the code under certain command line options, which is what you're also running into. That whole file needs some love; I've been playing around with some testing stuff so that we can start to do that kind of surgery without breaking things.

So yes, we have a handful of mutually exclusive options, some of which lead to code paths that are untested and incomplete.

I've been doing a lot of travel lately and am currently moving my family to the US, so I'm afraid I'm not in a position to make changes right now. The temporary workaround is to use a cspec. Some work was started in #191 to fix this, but it doesn't address the larger problem. However it is something we'd love to fix. If you're interested in taking a crack at it I'm happy to help, too.

**Comment by kbrowns** [comment]
Sean - thanks for all this context.  This really clears a lot of things
up.  I'll see what I can do to contribute to the cause.  Thanks again and
safe travels!

**Comment by kbrowns** [comment]
Sean - spent a fair amount of time looking at this today and I think I
understand what's going on much better.  One thing that I noticed that
seems wrong - or at a least under documented, is that if a --cspec is pass
in, as expected the customization specification is queried for on vsphere,
but unless there is also  "--disable-customization true" (undocumented
arg), the implementation with generate_clone_spec() subsequently tramples
on that fetched instance to a point where it no longer do what's defined on
vsphere.  It appears that implementation is trying to overly whatever was
passed in on the command line, but in doing so it kills the cspec.  In my
case I'm not even passing any other --c* arguments - only --cspec and it
still tramples it.

I suppose when the love you spoke of is applied to this code it might be
moot, but right now it doesn't appear --cspec works at all unless it's
accompanied by "--disable-customization true".

Can you confirm my general findings?  I'd like to contribute a PR back to
make this easier for the next guy, but want to have my thinking validated
first.

**Comment by kbrowns** [comment]
I need to retract some statements above.  I had some tainted tests that caused me to jump to some incorrect conclusions.  --cspec without --disable-customization true indeed works.  It does NOT trample on the fetched spec from vsphere.  However, the love you spoke is in need for when --cspec is not specific or other spec-ish settings are specified on the command line, but in addition to that, if --disable-customization true is specified, the fetched --cspec is never used.  I think that's a problem.  There is no means for telling the plugin to fetch the --cspec and do nothing else.  If all it was trying to do was overlay settings that were passed in on the command line, I think that would be acceptable because the "do nothing else" indicator would be to just not pass those things on the command line.  However, it's trying to look at the fetched --cspec and conditionally intervene - namely with identity.  That means that if someone in my org sets up a cspec in a specific state, it will trigger these issues and be pretty difficult to understand these downstream impacts.  

I don't know if this was the originally intent of --disable-customization as the name suggests it seems like to should be a way to turn off any intervening and use the --cspec specified as-is.  I think that can be accomplished if this logic was changed to include an else block where if --disable-customization true is specified use the --cspec as-is.  This will probably make a lot more sense in a PR which I intend to submit today, but wanted to retract my incorrect statements from last night to avoid confusion.

**Comment by swalberg** [comment]
Hi Kelly,

The `--disable-customization` option was here long before I started working on this project [introduced here](https://github.com/ezrapagel/knife-vsphere/commit/15abdd8d65fba2e9d8339ee285a3b34b99da80b8). My take on it (as I don't use it) is similar to yours.

If you're going to work on this section, there are a lot of double negatives in the code that could be cleaned up at the same time if you could. Rather than

```
unless a & b || c
  foo
else
  bar
```

It can be cleaned up to be

```
if a & b || c
  bar
else
  foo
end
```

or even better

```
if disable_all_extra_customizations?
  bar
else
  foo
end

private

def disable_all_extra_customizations?
  a & b || c
end
```

Thanks,

Sean

**Comment by swalberg** [comment]
Kelly, can we close this? I think it's resolved with your PR (thanks again)

**Comment by kbrowns** [comment]
yes, please
