### ISSUE TITLE
Remove dependency on chef gem

### ISSUE THREAD

**Issue by adamedx** [adamleff/knife-vsphere#197]
In general, it's a good idea for knife plugins to not take a gem dependency on the Chef gem, since it's understood that you need Chef to use knife anyway. This also avoids version conflicts -- currently the Ohai 8.6.0 gem can cause conflicts for people using Chef 12.4.1 and gem install knife-vsphere.

A fix could be to make the Chef dependency a dev dependency instead so that only bundler dev scenarios are affected.

**Comment by lamont-granquist** [comment]
For example:

https://github.com/chef/knife-ec2/blob/master/knife-ec2.gemspec#L22

**Comment by swalberg** [comment]
TIL, thank you. Can you look at #198 please?

**Comment by swalberg** [comment]
Just cut a release... 1.2.4 should be available shortly.

**Comment by adamedx** [comment]
Hey, thank you that works for everyone @swalberg !
